In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

from sklearn.preprocessing import StandardScaler

In [2]:
df_train=pd.read_csv("train.csv")
df_test=pd.read_csv("test.csv")

In [3]:
df_train.head(5)

         Date Procedure  n_Procedure  Temperature  EventTarget
0  12/11/2015         A            1           27            1
1  12/11/2015         B            1           27            1
2  12/11/2015         C            0           27            1
3  12/12/2015         A            3           21            0
4  12/12/2015         B            2           21            0

In [4]:
df_test

          Date  Temperature  EventTarget
0    11/1/2016           28            0
1    11/2/2016           29            0
2    11/3/2016           29            0
3    11/4/2016           32            0
4    11/5/2016           31            0
5    11/6/2016           34            0
6    11/7/2016           34            0
7    11/8/2016           27            0
8    11/9/2016           29            0
9   11/10/2016           31            2
10  11/11/2016           33            2
11  11/12/2016           27            2
12  11/13/2016           26            0
13  11/14/2016           33            0
14  11/15/2016           26            1
15  11/16/2016           30            1
16  11/17/2016           25            1
17  11/18/2016           30            0
18  11/19/2016           29            0
19  11/20/2016           30            0
20  11/21/2016           26            0
21  11/22/2016           31            0
22  11/23/2016           31            0
23  11/24/2016           25            0
24  11/25/2016           31            0
25  11/26/2016           31            0
26  11/27/2016           29            0
27  11/28/2016           25            0
28  11/29/2016           25            0
29  11/30/2016           29            0
30   12/1/2016           30            0
31   12/2/2016           31            0
32   12/3/2016           32            0
33   12/4/2016           30            0
34   12/5/2016           32            0
35   12/6/2016           30            2
36   12/7/2016           25            2
37   12/8/2016           28            2
38   12/9/2016           27            2
39  12/10/2016           25            2
40  12/11/2016           21            2

In [5]:
x_target = df_train['n_Procedure']
x_train = df_train.drop(['n_Procedure'],inplace=False,axis=1)

In [6]:
x_train['Date'] = pd.to_datetime(x_train['Date'], errors='coerce')
x_train['Month'] = x_train['Date'].dt.month
x_train['Day'] = x_train['Date'].dt.day
x_train.drop(['Date'],inplace=True,axis=1)
P_1 = [1 if x is 'A' else 0 for x in x_train['Procedure']]
P_2 = [1 if x is 'B' else 0 for x in x_train['Procedure']]
P_3 = [1 if x is 'C' else 0 for x in x_train['Procedure']]
x_train['P_1'] = P_1
x_train['P_2'] = P_2
x_train['P_3'] = P_3

In [7]:
x_train.drop(['Procedure'],inplace=True,axis=1)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(x_train, x_target, test_size=0.20, random_state=42)
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [19]:
regr = RandomForestRegressor(random_state=0)
regr.fit(X_train,y_train)

/home/akash/anaconda3/envs/my_env/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [20]:
y_pred=regr.predict(X_train)

In [24]:
y_pred_roundoff=np.round(y_pred)
y_pred_roundoff

array([ 1.,  4.,  9.,  2.,  0.,  6.,  3.,  2.,  4.,  1.,  3.,  5.,  4.,
        3.,  4.,  5.,  3.,  2.,  2.,  6.,  4.,  4.,  5.,  2.,  1.,  5.,
        5.,  6.,  4.,  6.,  2.,  3., 10.,  6.,  3.,  2.,  5.,  1.,  3.,
        4.,  2.,  4.,  3.,  2.,  3.,  5.,  2.,  7.,  2.,  6.,  4.,  4.,
        6.,  5.,  4.,  2.,  2.,  3.,  3.,  3.,  1.,  5.,  4.,  4.,  4.,
        5.,  3.,  2.,  6.,  3.,  2.,  7.,  7.,  5.,  4.,  3.,  4.,  4.,
        7.,  3.,  3.,  4.,  4.,  5.,  3.,  2.,  3.,  4.,  2.,  3.,  8.,
        6.,  3.,  5.,  6.,  3.,  3.,  7.,  4.,  5.,  2.,  6.,  6.,  3.,
        6.,  3.,  4.,  4.,  4.,  1.,  3.,  3.,  3.,  6.,  2.,  3.,  3.,
        3.,  3.,  3.,  4.,  3.,  4.,  3.,  4.,  6.,  8.,  1.,  2.,  3.,
        5.,  5.,  6.,  5.,  2.,  4.,  5.,  4.,  3.,  2.,  4.,  6.,  2.,
        7.,  3.,  8.,  4.,  2.,  3.,  5.,  2.,  3.,  3.,  2.,  2.,  3.,
        4.,  6.,  2.,  7.,  4.,  3.,  5.,  1.,  3.,  2.,  7.,  3.,  6.,
        3.,  9.,  6.,  1.,  3.,  3.,  3.,  4.,  5.,  3.,  4.,  4.,  5.,
        2.,  6.,  6.,  4.,  3.,  2.,  2.,  3.,  7.,  5.,  4.,  3.,  4.,
       10.,  1.,  5.,  4.,  4.,  5.,  7.,  1.,  2.,  4.,  2.,  5.,  4.,
        3.,  2.,  9.,  5.,  4.,  4.,  3.,  9.,  2.,  4.,  3.,  7.,  1.,
        3.,  2.,  1.,  4.,  4.,  4.,  3.,  3.,  6.,  2.,  5.,  6.,  2.,
        4.,  3.,  2.,  6.,  7.,  4.,  5.,  3.,  4.,  5.,  3.,  2.,  5.,
        6.,  4.,  3.,  4.,  6.,  2.,  5.,  4.,  4.,  1.,  4.,  2.,  3.,
        2.,  2.,  4.,  7.,  3.,  7.,  3.,  3.,  3.,  6.,  4.,  1.,  2.,
        6.,  4.,  5.,  4.,  1.,  1.,  4.,  7.,  4.,  4.,  7.,  4.,  3.,
        2.,  4.,  4.,  5.,  3.,  3.,  5.,  6.,  4.,  3.,  8.,  4.,  4.,
        3.,  3.,  7.,  5.,  4.,  3.,  5.,  2.,  7.,  7.,  1.,  3.,  1.,
        2.,  4.,  3.,  1.,  1.,  3.,  5.,  6.,  3.,  7.,  6.,  2.,  2.,
        2.,  1.,  6.,  5.,  6.,  4.,  0.,  4.,  3.,  0.,  4.,  2.,  5.,
        5.,  1.,  3.,  5.,  7.,  3.,  3.,  2.,  8.,  5.,  6.,  6.,  2.,
        3.,  4.,  6.,  3., 10.,  1.,  5.,  4.,  7.,  4.,  4.,  6.,  2.,
        2.,  5.,  2.,  8.,  1.,  2.,  2.,  6.,  1.,  3.,  0.,  3.,  8.,
        3.,  1.,  3.,  7.,  4.,  2.,  5.,  8.,  3.,  0.,  4.,  1.,  4.,
        4.,  3.,  3.,  3.,  4.,  5.,  4.,  2.,  2.,  3.,  2.,  2.,  6.,
        2.,  1.,  5.,  3.,  6.,  2.,  3.,  6.,  5.,  5.,  2.,  2.,  5.,
        2.,  3.,  6.,  4.,  6.,  4.,  4.,  5.,  6.,  6.,  6.,  8.,  3.,
        5.,  4.,  4.,  4.,  2.,  3.,  7.,  2.,  4.,  2.,  4.,  5.,  3.,
        2.,  3.,  3.,  4.,  5.,  3.,  4.,  7.,  4.,  3.,  2.,  2.,  4.,
        3.,  2.,  1.,  2.,  3.,  3.,  2.,  2.,  4.,  2.,  2.,  2.,  4.,
        4.,  3.,  3.,  4.,  3.,  2.,  6.,  6.,  3.,  4.,  3.,  2.,  6.,
        6.,  3.,  3.,  8.,  1.,  5.,  2.,  7.,  6.,  3.,  2.,  1.,  3.,
        5.,  4.,  4.,  1.,  0.,  4.,  3.,  4.,  8.,  2.,  3., 10.,  4.,
        6.,  3.,  4.,  2.,  4.,  6.,  7.,  4.,  1.,  2.,  4.,  4.,  7.,
        7.,  3.,  2.,  5.,  5., 10.,  5.,  5.,  5.,  3.,  2.,  0.,  5.,
        4.,  4.,  2.,  4.,  1.,  7.,  2.,  4.,  3.,  5.,  3.,  6.,  4.,
        7.,  4.,  3.,  2.,  2.,  3.,  4.,  4.,  2.,  6.,  4.,  3.,  0.,
        1.,  3.,  5.,  3.,  1.,  3.,  4.,  7.,  4.,  6.,  2.,  5.,  2.,
        6.,  5.,  6.,  3.,  2.,  4.,  2.,  2.,  3.,  4.,  2.,  3.,  4.,
        3.,  4.,  4.,  7.,  3.,  2.,  6.,  4.,  9.,  5.,  4.,  6.,  4.,
        7.,  2.,  6.,  2.,  3.,  1.,  2.,  3.,  6.,  2.,  4.,  5.,  0.,
        1.,  5.,  4.,  4.,  6.,  2.,  3.,  4.,  3.,  2.,  8.,  4.,  5.,
        6.,  3.,  6.,  2.,  2.,  4.,  5.,  0.,  4.,  2.,  3.,  3.,  3.,
        1.,  5.,  3.,  7.,  5.,  2.,  4.,  2.,  7.,  4.,  4.,  4.,  4.,
        4.,  4.,  7.,  3.,  3.,  2.,  3.,  6.,  4.,  2.,  2.,  2.,  4.,
        6.,  6.,  4.,  3.,  4.,  3.,  6.,  3.,  2.,  2.,  2.,  4.,  3.,
        7.,  2.,  5.,  5.,  3.,  3.,  1.,  2.,  2.,  4.,  5.,  3.,  4.,
        5.,  3.,  8.,  4.,  4.,  5.,  5.,  3.,  4.,  2.,  3.,  5.,  5.,
        5.,  2.,  3.,  2.,  1.,  3.,  4.,  7.,  4.,  5.,  4.,  5.,  7.,
        2.,  1.,  2.,  6.,  4.,  5.,  5.,  2.,  4.,  2.,  3.,  2.,  2.,
        3.,  7.,  4.,  5.,  4.,  3.,  2.,  3.,  6.,  3.,  3.,  3.,  4.,
        6.,  4.,  7.,  3.,  2.,  6.,  6.,  8.,  2.,  7.,  1.,  7.,  3.,
        2.,  3.,  3.,  4.,  1.,  1.,  4.,  4.,  1.,  5.,  2.,  5.,  5.,
        8.,  4.,  5.,  2.,  2.,  2.,  5.,  3.,  2.,  2.,  2.,  5.,  5.,
        7.,  7.])

In [25]:
print(np.exp(-mean_squared_error(y_train, y_pred)))
print(np.exp(-mean_squared_error(y_train, y_pred_roundoff)))

0.4536417132665693
0.4223619702817353

In [ ]:
y_pred=regr.predict(X_test)
y_pred_roundoff=np.round(y_pred)
print(np.exp(-mean_squared_error(y_train, y_pred)))
print(np.exp(-mean_squared_error(y_train, y_pred_roundoff)))